### ISSUE TITLE
Add environment definition file

### ISSUE THREAD

**Issue by matthewfeickert** [malin-horstmann/pyhf_pymc#1]
As you're using Conda for your virtual environment manager (totally fine) can you [add a Conda `environment.yml` file](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually) in a PR that would allow for replacing

https://github.com/malin-horstmann/pyhf_pymc/blob/0369604d211cbccd9031ac190fcf27df0771d639/README.md?plain=1#L7-L15

with just a

```
conda env create -f environment.yml
```

?

You can also unify these to all come from conda-forge as well so that you don't have to mix dependency managers.

* https://anaconda.org/conda-forge/pyhf
* https://anaconda.org/conda-forge/numpy
* https://anaconda.org/conda-forge/numpyro
* https://anaconda.org/conda-forge/matplotlib

**Comment by malin-horstmann** [comment]
Sure, thanks for commenting on that! It really wasn't very elegant ;) Hope it's better now

**Comment by matthewfeickert** [comment]
Thanks. Though in an environment definition file you don't want everything pinned to exact versions like this, you'd use [`conda-lock`](https://github.com/conda/conda-lock) to generate a lock file from the high level environment file instead (example of [paired `environment.yml` and `conda-lock.yml` files](https://github.com/iris-hep/analysis-systems-base/tree/f49b04c4520036716705fc1cec05e209effbdf00/docker) and [locking workflow](https://github.com/iris-hep/analysis-systems-base/blob/f49b04c4520036716705fc1cec05e209effbdf00/noxfile.py#L60-L75)).

Also we probably want to use `conda-forge` over

https://github.com/malin-horstmann/pyhf_pymc/blob/3e0568052b9e8b8b5a94a779189b1982c6c1802b/pyhf_pymc_env.yml#L2-L3

as that also allows for avoiding mixing `conda-forge` and PyPI installs (which is preferable to do to avoid dependency conflicts) and putting

https://github.com/malin-horstmann/pyhf_pymc/blob/3e0568052b9e8b8b5a94a779189b1982c6c1802b/pyhf_pymc_env.yml#L98

locks this to only working on your machine.

Can you open up a pull request to revise the environment file? We can iterate in the PR directly.

**Comment by matthewfeickert** [comment]
Sounds good and nothing to apologize for! I might take a stab at it later today and open a PR for you to check next week (you have a M1 mac, right?). It can be difficult to get environments that work across platforms sometimes with Conda, so sometimes you do need to mix and match with `pip` and that's fine.
