### ISSUE TITLE
Packaging resources

### ISSUE THREAD

**Issue by matthewfeickert** [malin-horstmann/pyhf_pymc#40]
We discussed some of this in a previous week, but to make some more concrete recommendations about packaging of the codebase I would recommend using [`hatch`/`hatchling`](https://hatch.pypa.io/latest/) given that all the code is pure-Python and so no binary extensions need to get built and packaged. For some more details of packaging a very simple example project see the PyPA's [Packaging Python Projects tutorial](https://packaging.python.org/en/latest/tutorials/packaging-projects/) which uses `hatchling` as one of their examples of a build backend. We can also discuss how packaging works.

`hatch` also has a way to create an example package setup.

Some specific notes about packaging related to the state of the repository at 5fbe7e0751cc7f9d9cd813a6d12c944b67513767:

* The package should only include source files, so the `.json` and `.ipynb` files

```console
$ git ls-files -- src/pyhf_pymc 
src/pyhf_pymc/HMC_inference.py
src/pyhf_pymc/MH_inference.py
src/pyhf_pymc/SRee_SRmm_Srem.json
src/pyhf_pymc/__init__.py
src/pyhf_pymc/prepare_inference.py
src/pyhf_pymc/sampling.ipynb
src/pyhf_pymc/ttbar_ljets_xsec_inclusive_pruned.json
```

should get moved out to something like a top level `examples/` directory (or something like that) in the repository. When the package is installed in a development mode (`python -m pip install --upgrade -e .`) you can still import the package normally in a notebook and then as you make edits to the package the changes will get automatically updated to the environment (e.g. the notebook) whenever the kernel is restarted.

* The package will need to list all the libraries that it directly depends on in the project [`dependencies` section](https://github.com/scikit-hep/pyhf/blob/b46b3f0cc005bdc4470bcaa0bfd2ae727a92ea1f/pyproject.toml#L45-L54) of the `pyproject.toml`. This will be the subset of things in [`environment.yml`](https://github.com/malin-horstmann/pyhf_pymc/blob/5fbe7e0751cc7f9d9cd813a6d12c944b67513767/environment.yml) that `pyhf-pymc` actually imports. An additional difference is that a package should only include _lower bounds_ of the dependencies which are the oldest versions that support the APIs and functionalities that `pyhf-pymc` relies on (in contrast to the current state of `environment.yml` which has them pinned to create a stable testing environment).

This last bit might be confusing as to the "why". I can explain this, but as an excellent (but long) inclusive summary I'd recommend reading sometime Henry Schreiner's [Should You Use Upper Bound Version Constraints?](https://iscinumpy.dev/post/bound-version-constraints/) and (probably before that) [App vs Library](https://iscinumpy.dev/post/app-vs-library/) blog posts.

I can also assist on a PR in terms of reviewing it before merge and giving feedback.

**Comment by malin-horstmann** [comment]
Thanks! I started on implementing your input. Regarding the lower version bounds .. Is there a nicer way to get them than just try and error?

**Comment by matthewfeickert** [comment]
This still hasn't been resolved (https://github.com/malin-horstmann/pyhf_pymc/pull/43#pullrequestreview-1384159872).

**Comment by matthewfeickert** [comment]
> Regarding the lower version bounds .. Is there a nicer way to get them than just try and error? (For now, I just used the environment bounds)

@malin-horstmann That's a good question. For right now just setting them to be the environment bounds is totally reasonable as the 3 of us are the only consumers of this package. :+1:

In general, you probably have a good idea of what APIs of the packages are being used and can roughly inform yourself on where to set these, but as you suspected the only way that I know of to _really_ check this is to empirically check. We do this once in `pyhf` and then we use [nightly CI](https://github.com/scikit-hep/pyhf/blob/d6208cbabb8ab727f201e6e06673f938d77b14b2/.github/workflows/lower-bound-requirements.yml) to check that we haven't change anything internally that would require a more modern version of our dependencies that requires a bump on the lower bounds.
